### ISSUE TITLE
When strongly-typed-Id is the type of Guid, some error occurs!

### ISSUE THREAD

**Issue by wztegon** [yangzhongke/LessCode.EFCore.StronglyTypedId#1]
When I use “new UserId();", there's no compile error in Visual Studio.
But if [strongly-typed-id] is the type of Guid, the new UserId is the default value of Guid and it's not what I want.
So why don't provide a parameterless constructor for Guid type, it just initializes the Guid type with "Guid.NewGuid()";
After doing that, when I use "new UserId();", I can get a correct Guid value instead of the default value(Guid.Empty)  of the structure;

**Comment by yangzhongke** [comment]
Thanks for your suggestion.
I have updated the project to support it.
![image](https://user-images.githubusercontent.com/13821363/208784694-9eb3e931-147e-451a-9c3b-bd394a02e13a.png)

Please upgrade LessCode.EFCore.StronglyTypedIdGenerator to the latest version.
