### ISSUE TITLE
Generates code in new root namespace

### ISSUE THREAD

**Issue by jeremysalwen** [yangzhongke/LessCode.EFCore.StronglyTypedId#2]
```
namespace My.Name.Space;

[HasStronglyTypedId(typeof(int))]
public class Dog
{
    [Key] public DogId Id { get; set; }
}
```
`DogId` gets put in a `Dogs` namespace, which I need to import first.  This doesn't seem appropriate, it's breaking out of the namespace I put it in.  It should be the `My.Name.Space.Dogs` namespace, or at least be user configurable.

**Comment by yangzhongke** [comment]
Thanks for your comment.
Bug fixed. Please update to the lastest version.
