### ISSUE TITLE
请问下IdClassTemplate和IdValueConverterTemplate的代码是由什么工具生成的?

### ISSUE THREAD

**Issue by z1qian** [yangzhongke/LessCode.EFCore.StronglyTypedId#4]
请问下IdClassTemplate和IdValueConverterTemplate的代码是由什么工具生成的?tt模板的内容是由这两个cs文件生成的吧?

**Comment by yangzhongke** [comment]
他们是从tt文件生成的。

**Comment by z1qian** [comment]
tt文件的代码是手敲的还是工具生成的呢?

**Comment by yangzhongke** [comment]
> tt文件的代码是手敲的还是工具生成的呢?

手敲，这个东西叫“t4 template”，具体网上搜吧。

**Comment by z1qian** [comment]
明白了,我在创建tt模板时应该选择 运行时文本模板,而不是 文本模板
![1717805658676](https://github.com/yangzhongke/LessCode.EFCore.StronglyTypedId/assets/87116820/b7862011-76a0-4a93-bb75-f9610ec560de)
