### ISSUE TITLE
多次调用生成的强类型id结构的构造函数

### ISSUE THREAD

**Issue by z1qian** [yangzhongke/LessCode.EFCore.StronglyTypedId#5]
![1718263303100](https://github.com/yangzhongke/LessCode.EFCore.StronglyTypedId/assets/87116820/c59c136c-e939-4e14-aec8-7af2186e1e3b)
会多次调用这边生成代码的构造函数,差不多有10几次
![1718263401436](https://github.com/yangzhongke/LessCode.EFCore.StronglyTypedId/assets/87116820/94dd542b-e5a8-4421-8918-130d1d2e68b5)

**Comment by yangzhongke** [comment]
这就是EFCore的执行方式导致的了，不是Bug。
